### PR TITLE
YOLOv7 usage docs updated 

### PR DESCRIPTION
**Pull request by faizan1234567**
When converting yolov7 weights to engine file, "model not supported" error appears. To solve, this I added yolov7 reparmeterization code and updated yolov7 usage docs.

### CODE REVIEW

**Comment by marcoslucianops** [comment]
Hello, the reparameterization must be done using the YOLOv7 repository because each model variation has a different code to do it.

**Comment by faizan1234567** [comment]
ok I mentioned that copy the script to yolov7 folder.

**Comment by marcoslucianops** [comment]
I meant, the steps are documented in YOLOv7 repo.

**Comment by faizan1234567** [comment]
Yeah. But when converting, many people won't have knowledge about that. It is an important, I think it should be mentioned in your yolov7 usage document in case if someone missed or doesn't. This is solve the problem, and it will save them time.

**Comment by faizan1234567** [comment]
I opened PR because I faced this issue. I spent quite a lot of time searching for the solution. If it was mentioned in your docs then it was super easy and time saving.

**Comment by marcoslucianops** [comment]
https://github.com/marcoslucianops/DeepStream-Yolo/pull/290

**Pull request closed without merging**
